spring:
  datasource:
    url: jdbc:postgresql://almox-postgresql:5432/almox
    username: postgres
    password: almox@123
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: update
      format_sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

redis-almox:
  url: redis://almox-redis:6379
  password: almox@123