spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/almox
    username: postgres
    password: almox@123
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: update
      format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      jdbc:
        lob:
          non_contextual_creation: true
    show-sql: true

