# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    container_name: almox_database
    restart: always
    environment:
      POSTGRES_PASSWORD: almox@123
    ports:
      - "5432:5432"
  redis:
    image: redis
    command: redis-server --appendonly yes
    hostname: redis
    ports:
      - "6379:6379"